name = "ImageColorThresholderApp"
uuid = "e253f47c-99a5-4462-a47e-a31f992eca7c"
authors = ["rakeshksr <rakeshksr@users.noreply.github.com>"]
version = "0.2.0"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
Aqua = "0.7"
ColorTypes = "0.11"
Makie = "0.19"
PrecompileTools = "1"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
